### PR TITLE
Major changes to how StarUpdater works

### PR DESCRIPTION
**Pull request by gnmmarechal**
Removed "updater" option from the updater, as the new way doesn't require it.
Removed old auto-updater, replaced it with an auto-updater at the beginning of the script.
Added a bootstrapper that fetches the latest script from a server and runs it.
CIA/3DSX files will now be StarUpdater bootstrappers - not StarUpdater itself.
This will make small updates easier (as they are server-sided only).
The CIA/3DSX will only be updated if the LPP binary or the bootstrapper need to be updated (hopefully they won't).

### CODE REVIEW

**Comment by gnmmarechal** [comment]
I've finished reading everything again, I think I fixed all syntax and other stupid errors.

**Comment by gnmmarechal** [comment]
Huh. I'm not entirely sure , but do the self updaters actually print any text to the screen? Lel

Huh, it is only a minor issue if it doesn't though. The CIA/3DSX are small, so it won't hang there. I guess.

I'll look into that later.

**Comment by astronautlevel2** [comment]
Unfortunately I don't think I'm going to merge this. I don't like the idea of having two different scripts, one used only for downloading the main script.

**Comment by gnmmarechal** [comment]
Why not? Would you rather have the updater break every time a chance happens and have to issue an update to the CIA/3DSX itself?

**Pull request closed without merging**
